export const GET_DATA_REQUEST="GET_DATA_REQUEST"
export const GET_DATA_SUCCESS="GET_DATA_SUCCESS"
export const GET_DATA_FAILURE="GET_DATA_FAILURE"

export const SAVE_LOGGED_DATA="SAVE_LOGGED_DATA"

export const SEARCH_PINCODE_REQUEST="SEARCH_PINCODE_REQUEST"
export const SEARCH_PINCODE_SUCCESS="SEARCH_PINCODE_SUCCESS"
export const SEARCH_PINCODE_FAILURE="SEARCH_PINCODE_FAILURE"

export const SEND_ALERT="SEND_ALERT"

export const HANDLE_LOGOUT="HANDLE_LOGOUT"